- name: play level variable
  hosts: local
  connection: local
  vars:
    organization: "WBG"
    department: "IT"
    roll: "DevOps"

  tasks:
  - name: print message
    vars:
      organization: "Bellhopat"        
    ansible.builtin.debug:
        msg: " Working: {{ organization }}, area: {{ department }} , designation: {{ roll }}"