- name: type of variable
  hosts: local
  connection: local
  vars_files:
  - detail.yaml
  tasks:
  - name: print variable values
    ansible.builtin.debug:
        msg: " Working: {{ organization }}, area: {{ department }} , designation: {{ roll }}"