- name: type of variable
  hosts: local
  connection: local
  vars_files:
  - details.yaml
  tasks:
  - name: print message
      ansible.builtin.debug:
        msg: " Working: {{ organization }}, area: {{ department }} , designation: {{ roll }}"