
- name: type of variable
  hosts: local
  connection: local
  vars_files:
  IS_live: true
  tasks:
  - name: check live or not
    ansible.builtin.debug:
       msg: "this is live server"
    when: IS_live