- name: mongodb configuration
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mongodb.repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: start and enable mongodb
      ansible.builtin.service:
        name: mongod
        enabled: yes
        state: started

    - name: allow replace the ip address in /etc/hosts
      ansible.builtin.replace:
      path: /etc/hosts
      regexp: '127.0.0.1'
      replace: '0.0.0.0' 
      backup: yes  # Recommended: creates a timestamped backup copy first
    - name: restart mongodb
      ansible.builtin.service:
       name: mongod
       state: restarted
