- name: ec2 and rout53 recodes 
  hosts: all
  connection: local
  vars:
    SG_id: sg-0718c2c4c36982ff9
    ami_id: ami-081b0a6eac00b4f53
    envt: dev
    domain_name: fazarulla.online 
    instance:
     - mongodb
     - catalogue 
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: 't3.micro'
      security_group: "{{ SG_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ envt }}"
      tags:
        project: "roboshop"
        component: "{{ item }}"
        Environment: "{{ envt }}"
        name: "{{ item }}-{{ envt }}"

    loop: "{{ instance }}"
    register: ec2_output

  - name: output of ec2 instance
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: Create route53 recodes
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ envt }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}" 

